# Generated by Django 5.2.17 on 2026-08-14 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(choices=[('sido', '시/도'), ('sigungu', '시/군구'), ('dong', '읍/면/동')], max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pools.region')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'level', 'parent')},
            },
        ),
    ]
