# Generated by Django 5.2.17 on 2026-08-14 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='district',
        ),
        migrations.AddField(
            model_name='pool',
            name='dong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pools', to='pools.region'),
        ),
    ]
