# Generated by Django 5.2.17 on 2026-08-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('redness', '붉음 반응형'), ('dry', '건조·당김형'), ('itchy', '가려움 반응형'), ('trouble', '트러블 반응형'), ('none', '이상 없음'), ('needs_check', '전문 확인 필요')], max_length=20)),
                ('change_summary', models.TextField()),
                ('comparison_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('swim_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='records.swimrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
