# Generated by Django 5.2.17 on 2026-08-14 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIanalysis', '0001_initial'),
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_types', models.JSONField(default=list)),
                ('pattern_description', models.TextField(blank=True)),
                ('symptom_changes', models.JSONField(default=list)),
                ('four_week_trend', models.JSONField(blank=True, default=list)),
                ('clinic_recommended', models.BooleanField(default=False)),
                ('clinic_trigger_reason', models.CharField(blank=True, choices=[('score_streak', '증상 점수 연속 3회 이상 상승'), ('persisted_72h', '증상 72시간 이상 지속'), ('recurring_2w', '최근 2주 내 반복 악화'), ('photo_diff_severe', '얼굴 사진에서 수영 전후 차이가 심함')], max_length=20, null=True)),
                ('disclaimer', models.CharField(default='AI 분석은 참고용이며, 의료 진단을 대체하지 않습니다.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('swim_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='records.swimrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AIAnalysis',
        ),
    ]
