# Generated by Django 5.2.17 on 2026-08-14 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('swim_count', models.PositiveIntegerField(default=0)),
                ('avg_swim_duration', models.PositiveIntegerField(default=0)),
                ('symptom_trend', models.JSONField(blank=True, default=list)),
                ('recommended_ingredients', models.JSONField(blank=True, default=list)),
                ('recommended_products', models.JSONField(blank=True, default=list)),
                ('clinic_recommended', models.BooleanField(default=False)),
                ('other_pool_recommended', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='RoutineRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_swim_count', models.PositiveIntegerField()),
                ('recommended_swim_minutes', models.PositiveIntegerField()),
                ('skin_care_routine', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weekly_report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='report.weeklyreport')),
            ],
        ),
    ]
