# Generated by Django 5.2.17 on 2026-08-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routinerecommendation',
            name='condition_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='routinerecommendation',
            name='intensity_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
