# Generated by Django 5.2.17 on 2026-08-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskinprofile',
            name='skin_type',
        ),
        migrations.AlterField(
            model_name='userskinprofile',
            name='avg_swim_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userskinprofile',
            name='swim_period',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userskinprofile',
            name='weekly_swim_count',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='UserSkinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_types', to='accounts.userskinprofile')),
            ],
        ),
    ]
