# Generated by Django 6.0.3 on 2026-08-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userskinprofile_skin_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='terms_type',
            field=models.CharField(choices=[('TERMS_OF_SERVICE', '이용약관'), ('PRIVACY_POLICY', '개인정보 처리방침'), ('THIRD_PARTY_DERNA', '개인정보 제3자 제공 동의서(Derna)'), ('THIRD_PARTY_SWIN', '개인정보 제3자 제공 동의서(SWin)'), ('SENSITIVE_INFO', '민감정보 수집·이용 동의서'), ('MARKETING', '마케팅 정보 수신 동의서')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='agreement',
            unique_together={('user', 'terms_type')},
        ),
    ]
