# Generated by Django 5.2.17 on 2026-08-14 15:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='clinicreservation',
            name='calendar_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clinicreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinicreservation',
            name='trigger_reason',
            field=models.CharField(blank=True, choices=[('score_streak', '증상 점수 연속 3회 이상 상승'), ('photo_diff_severe', '얼굴 사진에서 수영 전후 차이가 심함')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clinicreservation',
            name='trigger_swim_record_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='clinicreservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clinicreservation',
            name='user_consented',
            field=models.BooleanField(default=False, verbose_name='자료 전달 동의 여부'),
        ),
        migrations.AddField(
            model_name='clinicreservation',
            name='user_note',
            field=models.TextField(blank=True, verbose_name='사용자 기타 메모(요청사항)'),
        ),
        migrations.AlterField(
            model_name='clinicreservation',
            name='clinic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='clinic.clinic'),
        ),
        migrations.AlterField(
            model_name='clinicreservation',
            name='status',
            field=models.CharField(choices=[('recommended', '권장됨'), ('booked', '예약됨'), ('completed', '방문 완료'), ('cancelled', '취소됨')], default='recommended', max_length=15),
        ),
        migrations.AlterField(
            model_name='clinicreservation',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinicreservation',
            name='visit_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ClinicReferral',
        ),
    ]
