# Generated by Django 5.2.17 on 2026-08-16 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_clinic_address_clinicreservation_calendar_synced_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clinicreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'booked')), fields=('clinic', 'visit_date', 'visit_time'), name='unique_booked_clinic_slot'),
        ),
    ]
