# Generated by Django 5.2.17 on 2026-08-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinicreservation_unique_booked_clinic_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicreservation',
            name='treatment_items',
            field=models.JSONField(blank=True, default=list, verbose_name='시술 내역'),
        ),
    ]
