# Generated by Django 5.2.17 on 2026-08-10 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwimRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swim_records', to='pools.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swim_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SkinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.CharField(choices=[('before', '수영 전'), ('after', '수영 후'), ('additional', '추가 기록')], max_length=20)),
                ('symptom_type', models.CharField(choices=[('redness', '붉음 반응형'), ('dry', '건조·당김형'), ('itchy', '가려움 반응형'), ('trouble', '트러블 반응형'), ('none', '이상 없음'), ('needs_check', '전문 확인 필요')], max_length=20)),
                ('symptom_level', models.PositiveSmallIntegerField()),
                ('memo', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='skin_records/%Y/%m/')),
                ('swim_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_records', to='records.swimrecord')),
            ],
        ),
    ]
