# Generated by Django 6.0.3 on 2026-08-16 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swimrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='swimrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='swimrecord',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='swimrecord',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='swimrecord',
            name='start_time',
        ),
        migrations.AddField(
            model_name='swimrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swimrecord',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='swimrecord',
            name='parent_record',
            field=models.ForeignKey(blank=True, help_text='추가 기록일 경우 원본 수영 기록 참조', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_records', to='records.swimrecord'),
        ),
        migrations.AddField(
            model_name='swimrecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='swim_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='swimrecord',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swim_records', to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='swimrecord',
            name='swim_time',
            field=models.CharField(blank=True, choices=[('30분 미만', '30분 미만'), ('30~60분', '30~60분'), ('60~90분', '60~90분'), ('90분 이상', '90분 이상')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='swimrecord',
            name='timing',
            field=models.CharField(choices=[('BEFORE', '수영 전'), ('AFTER', '수영 후'), ('ADD', '추가 기록')], default='BEFORE', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SwimRecordSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_type', models.CharField(help_text='당김, 건조, 가려움, 붉음, 여드름 등', max_length=20)),
                ('score', models.CharField(choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=5)),
                ('swim_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='records.swimrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='SkinRecord',
        ),
    ]
