# Generated by Django 6.0.3 on 2026-08-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['start_datetime']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='repeat_option',
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeat_count',
            field=models.PositiveIntegerField(blank=True, help_text='반복 횟수', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeat_end_type',
            field=models.CharField(blank=True, choices=[('FOREVER', '계속 반복'), ('COUNT', '일정 횟수 반복'), ('UNTIL_DATE', '종료 날짜')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeat_group_id',
            field=models.UUIDField(blank=True, help_text='반복 일정 묶음 식별용 UUID', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeat_interval_weeks',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='N주마다 반복', null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='repeat_until',
            field=models.DateField(blank=True, help_text='반복 종료 날짜', null=True),
        ),
    ]
